### ISSUE TITLE
titalpower and windpower problem in shard LuaAI environment

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#8]
the tidal and wind power are get the first time and after this will become always 0

**Comment by eronoobos** [comment]
Yeah, I was noticing that with tidal. `map:TidalStrength()` always got the right number, but `tidalPower`, the global variable set in that horrific monster, `CheckForMapControl`, goes back to 0 for some reason. In retrospect, I have no idea why I started using `tidalPower` instead of getting `map:TidalStrength()` directly.

**Comment by pandaro** [comment]
fixed i hope so i close
